# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run CSSR Algorithm
#'
#' Write some docs!
#'
#' @param alphabet String representing alphabet
#' @param data String representing discrete-state time series data
#' @param maxLength Maximum history length
#' @param isChi Boolean to indicate whether to perform chi-square test
#' @param sigLevel Significant level
#' @param outputPrefix Prefix for output files
#'
#' @export
runCSSR <- function(alphabet, data, maxLength, isChi, sigLevel, outputPrefix) {
    .Call('CSSR_runCSSR', PACKAGE = 'CSSR', alphabet, data, maxLength, isChi, sigLevel, outputPrefix)
}

