# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run CSSR Algorithm
#'
#' Write some docs!
#'
#' @param alphabet something
#' @param data something
#' @param maxLength something
#' @param chiSquare something
#' @param sigLevel something
#'
#' @export
runCSSR <- function(alphabet, data, maxLength, isMulti=false, isChi=false, sigLevel = 0.001, outputPrefix) {
    .Call('runCSSR', PACKAGE='CSSR', alphabet, data, maxLength, isMulti, isChi, sigLevel, outputPrefix)
}

